name: nd3-env 
channels:
  - pytorch
  - nvidia # for CUDA packages
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # use this line if you want CPU
  # - cpuonly  # use this line if you want GPU

  - pip:
      - gymnasium[mujoco]
      - mujoco
      - imageio
      - imageio-ffmpeg
      - tqdm
      - wakepy