name: nd3-env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly  # remove this line if you want GPU (see below)
  - pip:
      - gymnasium[mujoco]
      - mujoco
      - imageio
      - imageio-ffmpeg
      - tqdm